### ISSUE TITLE
how to score

### ISSUE THREAD

**Issue by kumavis** [SabakiHQ/go-board#6]
(suppose it depends on what rules you are using but)
how to count territory?

**Comment by kumavis** [comment]
i had no idea
woof
https://www.reddit.com/r/baduk/comments/13dt8t/help_writing_a_scoring_algorithm_for_a_go_game/
https://web.archive.org/web/20170701063603/http://www.andromeda.com/people/ddyer/go/scoring-games.html

**Comment by apetresc** [comment]
Right; as you've found, scoring a game is not really part of the "state" of the board (which is all this library attempts to handle), but rather a semantic property of the game and its ruleset.

Out of curiosity, what is your use case? There are relatively painless ways to automate scoring, depending on your project, using an engine as the backend, etc.
