### ISSUE TITLE
Possible redundant line?

### ISSUE THREAD

**Issue by tangjm** [SabakiHQ/go-board#7]
What's the reasoning behind this line https://github.com/SabakiHQ/go-board/blob/927573aa72ea88558653b085a3efaed721cc5b31/src/GoBoard.js#L55?

Is it to allow for flexibility in letting us use any positive integer to represent Black and any negative integer to represent White? 
I think this would, however, never see its use if we made use of the type file.

**Comment by yishn** [comment]
I didn't want to throw an error for invalid values of `sign`.
